/// Flutter icons EncapitalIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EncapitalIcons
///      fonts:
///       - asset: fonts/EncapitalIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class EncapitalIcons {
  EncapitalIcons._();

  static const _kFontFam = 'EncapitalIcons';
  static const _kFontPkg = null;

  static const IconData portfolio_outline =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_outlined =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watchlist_outlined =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watchlist_filled =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portfolio_filled =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderbook_outlined =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderbook_filled =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
